name: Frontend CI/CD Pipeline

on: 
    push: 
        branches: [main, develop]
        paths:
            - 'frontend/**'

    pull_request: 
        branches: [main, develop]
        paths:
            - 'frontend/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm ci
              working-directory: ./frontend

            - name: Lint code
              run: npm run lint
              working-directory: ./frontend

            - name: Run tests
              run: npm test
              working-directory: ./frontend

            - name: Build app
              run: npm run build
              working-directory: ./frontend

            - name: Deploy to staging
              run: echo "Add frontend deployment script here"
              env:
                STAGING_ENV: ${{ secrets.STAGING_ENV }}